spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: eureka-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true

server:
  port: 8070
